steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:$COMMIT_SHA' # Tag with commit SHA
      - '--tag'
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:latest' # Also tag with latest
      # --- Build Arguments using $$ syntax ---
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=$$FIREBASE_API_KEY' # Use $$VAR_NAME from availableSecrets
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN' # Use $$VAR_NAME
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID' # Use $$VAR_NAME
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET' # Use $$VAR_NAME
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID' # Use $$VAR_NAME
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=$$FIREBASE_APP_ID' # Use $$VAR_NAME
      # --- End Build Arguments ---
      - '--platform' # Specify platform for Cloud Run compatibility
      - 'linux/amd64'
      - '.' # Build context is the current directory
    # --- ADD secretEnv BACK IN to satisfy validator ---
    secretEnv:
      - 'FIREBASE_API_KEY'
      - 'FIREBASE_AUTH_DOMAIN'
      - 'FIREBASE_PROJECT_ID'
      - 'FIREBASE_STORAGE_BUCKET'
      - 'FIREBASE_MESSAGING_SENDER_ID'
      - 'FIREBASE_APP_ID'

  # 2. Push the Docker image to Artifact Registry
  # ... (rest of push step is the same)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app'

  # 3. Deploy the image to Cloud Run
  # ... (rest of deploy step is the same)
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:$COMMIT_SHA'
      - '--service'
      - 'skillsculpt-app'
      - '--region'
      - 'us-west2'
      - '--platform'
      - 'managed'
      - '--project'
      - 'car-magic-454906'
      # - '--allow-unauthenticated' # Uncomment if needed
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'

# images section remains the same
images:
  - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:$COMMIT_SHA'
  - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:latest'

# availableSecrets section remains the same
availableSecrets:
  secretManager:
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: 'FIREBASE_API_KEY'
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'FIREBASE_AUTH_DOMAIN'
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: 'FIREBASE_PROJECT_ID'
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'FIREBASE_STORAGE_BUCKET'
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: 'FIREBASE_APP_ID'

# substitutions section remains the same
substitutions:
  _SERVICE_NAME: skillsculpt-app
  _CLOUD_RUN_REGION: us-west2
  _ARTIFACT_REGISTRY_REGION: us-west2
  _ARTIFACT_REPO_NAME: skillsculpt-repo

# timeout section remains the same
timeout: '1200s' # 20 minutes

# options section remains the same
options:
  logging: CLOUD_LOGGING_ONLY