# cloudbuild.yaml (Corrected Placement of availableSecrets)

# Timeout for the build
timeout: '1200s' # 20 minutes

# Define substitutions used in the build
substitutions:
  _SERVICE_NAME: skillsculpt-app
  _CLOUD_RUN_REGION: us-west2
  _ARTIFACT_REGISTRY_REGION: us-west2
  _ARTIFACT_REPO_NAME: skillsculpt-repo

steps:
# -----------------------------------------
# STEP 0: Debug Secrets Passed as Env Vars
# Uses the environment variables made available globally by the top-level availableSecrets block.
# -----------------------------------------
- name: 'ubuntu'
  id: DebugSecrets
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "--- DEBUGGING BUILD ENV VARS (Standardized Names) ---"
    echo "API Key Env Var: [$$NEXT_PUBLIC_FIREBASE_API_KEY]"
    echo "Auth Domain Env Var: [$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN]"
    echo "Project ID Env Var: [$$NEXT_PUBLIC_FIREBASE_PROJECT_ID]"
    echo "Storage Bucket Env Var: [$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET]"
    echo "Messaging Sender ID Env Var: [$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID]"
    echo "App ID Env Var: [$$NEXT_PUBLIC_FIREBASE_APP_ID]"
    echo "-----------------------------------------------------"
  # NO availableSecrets block needed INSIDE the step here

# -----------------------------------------
# STEP 1: Build Docker Image
# Uses standardized NEXT_PUBLIC_... env vars (from top-level availableSecrets)
# for substitution into build args.
# -----------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    # Tagging
    - '--tag'
    - '${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA'
    - '--tag'
    - '${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:latest'
    # Build Arguments using standardized $$NEXT_PUBLIC_... substitution
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_API_KEY=$$NEXT_PUBLIC_FIREBASE_API_KEY'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$NEXT_PUBLIC_FIREBASE_PROJECT_ID'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_APP_ID=$$NEXT_PUBLIC_FIREBASE_APP_ID'
    # Specify platform
    - '--platform'
    - 'linux/amd64'
    # Build context
    - '.'
  # NO availableSecrets block needed INSIDE the step here

# -----------------------------------------
# STEP 2: Push Docker Image to Artifact Registry
# Pushing with --all-tags ensures both :latest and :$COMMIT_SHA are pushed
# -----------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - '--all-tags' # Push both commit sha and latest tags
    - '${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}'
  waitFor: ['Build'] # Depends on Build step

# -----------------------------------------
# STEP 3: Deploy to Cloud Run
# Deploys the ':latest' image.
# -----------------------------------------
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - '${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:latest'
    - '--region'
    - '${_CLOUD_RUN_REGION}'
    - '--platform'
    - 'managed'
    - '--project'
    - '${PROJECT_ID}' # Use built-in substitution PROJECT_ID
    # - '--allow-unauthenticated' # Uncomment if needed
    - '--quiet' # Suppress interactive prompts
  waitFor: ['Push'] # Depends on Push step

# List of images created by the build (for GCB metadata)
images:
  - '${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:latest'

# ---- TOP-LEVEL availableSecrets Block ----
# This makes secrets available as environment variables to ALL build steps.
# Standardized to use NEXT_PUBLIC_... env var names directly.
availableSecrets:
  secretManager:
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_API_KEY' # Standardized name
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN' # Standardized name
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID' # Standardized name
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET' # Standardized name
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID' # Standardized name
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_APP_ID' # Standardized name

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Specify the service account for the trigger (due to org policy)
# --- Replace YOUR_TRIGGER_SERVICE_ACCOUNT_EMAIL ---
# serviceAccount: projects/car-magic-454906/serviceAccounts/YOUR_TRIGGER_SERVICE_ACCOUNT_EMAIL