steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag'
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:$COMMIT_SHA' # Tag with commit SHA
      - '--tag'
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:latest' # Also tag with latest
      # --- CORRECTED Build Arguments using $$ syntax ---
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=$$FIREBASE_API_KEY' # Use $$VAR_NAME syntax from availableSecrets
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN' # Use $$VAR_NAME syntax
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID' # Use $$VAR_NAME syntax
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET' # Use $$VAR_NAME syntax
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID' # Use $$VAR_NAME syntax
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=$$FIREBASE_APP_ID' # Use $$VAR_NAME syntax
      # --- End Corrected Build Arguments ---
      - '--platform' # Specify platform for Cloud Run compatibility
      - 'linux/amd64'
      - '.' # Build context is the current directory
    # secretEnv block is removed as $$ accesses availableSecrets directly in args

  # 2. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app' # Push all tags associated with this image name

  # 3. Deploy the image to Cloud Run
  - name: 'gcr.io/google-appengine/exec-wrapper' # Uses gcloud command via wrapper
    args:
      - '-i' # Image argument for the wrapper
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:$COMMIT_SHA'
      - '--service'
      - 'skillsculpt-app' # Your Cloud Run service name
      - '--region'
      - 'us-west2' # Your Cloud Run service region
      - '--platform'
      - 'managed' # Specify managed platform
      - '--project'
      - 'car-magic-454906'
      # --- IMPORTANT ---
      # Does your service need to be publicly accessible? If YES, uncomment the next line:
      # - '--allow-unauthenticated'
      # If NO (it requires authentication), leave it commented out or remove it.
    entrypoint: 'gcloud' # Command to run inside the wrapper
    args: # Arguments for the gcloud command (entrypoint)
      - 'run'
      - 'deploy'

# Define the images to be pushed after the build completes successfully
images:
  - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:$COMMIT_SHA'
  - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:latest'

# Define which secrets Cloud Build needs access to (this section remains the same)
availableSecrets:
  secretManager:
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: 'FIREBASE_API_KEY' # Used by $$FIREBASE_API_KEY in args
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'FIREBASE_AUTH_DOMAIN' # Used by $$FIREBASE_AUTH_DOMAIN
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: 'FIREBASE_PROJECT_ID' # Used by $$FIREBASE_PROJECT_ID
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'FIREBASE_STORAGE_BUCKET' # Used by $$FIREBASE_STORAGE_BUCKET
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'FIREBASE_MESSAGING_SENDER_ID' # Used by $$FIREBASE_MESSAGING_SENDER_ID
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: 'FIREBASE_APP_ID' # Used by $$FIREBASE_APP_ID

# Define substitution variables (already filled with your known values)
substitutions:
  _SERVICE_NAME: skillsculpt-app
  _CLOUD_RUN_REGION: us-west2
  _ARTIFACT_REGISTRY_REGION: us-west2
  _ARTIFACT_REPO_NAME: skillsculpt-repo

# Optional: Set timeout for the build
timeout: '1200s' # 20 minutes

# Specify logging option required when using a custom/specified service account
options:
  logging: CLOUD_LOGGING_ONLY