steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '--no-cache'
      - '--tag'
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:$COMMIT_SHA'
      - '--tag'
      - 'us-west2-docker.pkg.dev/car-magic-454906/skillsculpt-repo/skillsculpt-app:latest'
      - '--platform'
      - 'linux/amd64'
      - '.'
    # REMOVE the secretEnv section from this step
    # secretEnv:
    #   - 'FIREBASE_API_KEY'
    #   ... etc ...
    # ADD volumes section to mount secrets into /secrets directory
    volumes:
      - name: 'firebase-secrets-vol' # Arbitrary volume name
        path: '/secrets'            # Mount point inside this build step's container

  # 2. Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    # ... (push step remains the same) ...

  # 3. Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    # ... (deploy step remains the same) ...

# images section
# ... (remains the same) ...

# availableSecrets section: Change 'env' to 'volume' and 'fileName'
availableSecrets:
  secretManager:
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      volume: 'firebase-secrets-vol'  # Use volume name defined above
      fileName: 'FIREBASE_API_KEY'    # File name within the path (/secrets/FIREBASE_API_KEY)
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      volume: 'firebase-secrets-vol'
      fileName: 'FIREBASE_AUTH_DOMAIN' # /secrets/FIREBASE_AUTH_DOMAIN
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      volume: 'firebase-secrets-vol'
      fileName: 'FIREBASE_PROJECT_ID'   # /secrets/FIREBASE_PROJECT_ID
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      volume: 'firebase-secrets-vol'
      fileName: 'FIREBASE_STORAGE_BUCKET'# /secrets/FIREBASE_STORAGE_BUCKET
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      volume: 'firebase-secrets-vol'
      fileName: 'FIREBASE_MESSAGING_SENDER_ID'# /secrets/FIREBASE_MESSAGING_SENDER_ID
    - versionName: projects/car-magic-454906/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      volume: 'firebase-secrets-vol'
      fileName: 'FIREBASE_APP_ID'      # /secrets/FIREBASE_APP_ID

# substitutions section
# ... (remains the same) ...

# timeout section
# ... (remains the same) ...

# options section
# ... (remains the same) ...